spring.application.name=orm-learn

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/QuizDB
spring.datasource.username=postgres
spring.datasource.password=UMAsri@3016
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Logging
logging.level.org.springframework=INFO
logging.level.com.cognizant=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE