spring.application.name=orm-learn

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/ormlearn_hql
spring.datasource.username=postgres
spring.datasource.password=UMAsri@3016

# JPA Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.org.springframework=INFO
logging.level.com.cognizant=DEBUG
logging.level.org.hibernate.SQL=DEBUG